version: '3'

services:
  ecom-service:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '11234:11234'
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '400M'

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'  # Map NGINX to port 8080 on localhost
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mount custom NGINX configuration file
